# Config for training on full TuSimple dataset with ResNet-34
dataset: tusimple
log:
  out_dir: experiments/runs/tusimple_resnet34

# This will be passed to LaneATT
laneatt:
  config: laneatt_tusimple_resnet34.yml
  epochs: 100
