dataset: tusimple
paths: configs/paths.yaml

train:
  batch_size: 4
  num_epochs: 2
  num_workers: 4
  lr: 1e-4
  device: cuda

model:
  name: laneatt
  backbone: resnet34
  pretrained: true
  
log:
  out_dir: experiments/runs/tusimple_debug
  save_every: 1