# Config for training on full TuSimple dataset with ResNet-122
dataset: tusimple
log:
  out_dir: experiments/runs/tusimple_resnet122

# This will be passed to LaneATT
laneatt:
  config: laneatt_tusimple_resnet122.yml
  epochs: 100
