# Config for training on full TuSimple dataset with ResNet-18
dataset: tusimple
log:
  out_dir: experiments/runs/tusimple_resnet18

# This will be passed to LaneATT
laneatt:
  config: laneatt_tusimple_resnet18.yml
  epochs: 100
